###### /auth ######
### Create a User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "shimopino",
    "email": "shimopino@example.com",
    "password": "shimopino"
}

### Login a User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "shimopino@example.com",
    "password": "shimopino"
}

### Check a Token
GET http://localhost:3000/auth/me

### Logout a User
POST http://localhost:3000/auth/signout

### Refresh a Token
GET http://localhost:3000/auth/refresh

###### /tasks ######
### Get all tasks
GET http://localhost:3000/tasks

### Create a Task
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "サンプルTODO",
    "content": "サンプルとして追加したTODOリストの1つ",
    "expires": "2021-11-22T12:00:00+09:00"
}

### Get a Task by Id
GET http://localhost:3000/tasks/2YJzdhI2MYqRa0_C7AcJW

### Delete a Task
DELETE http://localhost:3000/tasks/2YJzdhI2MYqRa0_C7AcJW

### Done a Task
PATCH http://localhost:3000/tasks/2YJzdhI2MYqRa0_C7AcJW/done
