### Create a User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "shimopino",
    "email": "shimopino@example.com",
    "password": "shimopino"
}

### Login a User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "shimopino@example.com",
    "password": "shimopino"
}

### Check a Token
GET http://localhost:3000/auth/me